name: Veracode Governance Scan

on:
  workflow_dispatch:
  schedule:
    # Runs "Every Sunday" (see https://crontab.guru)
    - cron: '5 8 * * Sun'

jobs:
  Checkout_Artifact_Scan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
# Security Scan Mainline       

    - name: Directory List
      run: ls -la
      
    - name: Get Veracode
      uses: wei/curl@master
      with:
        args: -sS -o VeracodeJavaAPI.jar "https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/19.6.5.8/vosp-api-wrappers-java-19.6.5.8.jar"

    - name: Start SAST / SCA Governance Scan      
      run: java -jar VeracodeJavaAPI.jar -action uploadandscan -vid ${{ secrets.VERACODE_API_ID }} -vkey ${{ secrets.VERACODE_API_KEY }} -appname GitHub-VeraDemoDotNetCore -createprofile true -version "GitHub Actions job $GITHUB_RUN_NUMBER" -filepath artifacts/VeraDemoDotNetCoreAppArtifact.zip
