name: Veracode Governance Scan

on:
  workflow_dispatch:
  schedule:
    # Runs "Every Sunday" (see https://crontab.guru)
    - cron: '5 8 * * Sun'

jobs:
  Veracode_Governance_Scan:

    runs-on: ubuntu-latest
    container: 
      image: veracode/api-wrapper-java:latest
      options: --user root
    steps:
    - uses: actions/checkout@v3
        
# Security Scan Mainline Branch / Goveranance SAST and SCA scan      

    - name: scan
      run: |
        java -jar /opt/veracode/api-wrapper.jar -vid ${{secrets.VERACODE_ID}} -vkey ${{secrets.VERACODE_KEY}} -action UploadAndScan -createprofile false -appname GitHub-VeraDemoDotNetCore -version "${{ github.run_id }}" -filepath artifacts/VeraDemoDotNetCoreAppArtifact.zip
