name: Veracode Governance Scan

on:
  workflow_dispatch:
  schedule:
    # Runs "Every Sunday" (see https://crontab.guru)
    - cron: '5 8 * * Sun'

jobs:
  Checkout_Artifact_Scan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
# Security Scan        

    - name: Directory List
      run: ls -la
      
    - name: Veracode SAST and SCA Governance Scan
      uses: veracode/veracode-uploadandscan-action@0.2.1
      with:
        appname: 'GitHub-VeraDemoDotNetCore'
        createprofile: false
        filepath: 'artifacts/VeraDemoDotNetCoreAppArtifact.zip'
        vid: '${{ secrets.API_ID }}'
        vkey: '${{ secrets.API_KEY }}'
